version: '2.1'

services:
  movies-db:
    container_name: movies-db
    build: ./movies/src/db/
    ports:
      - '5434:5432' # HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-db:
    container_name: users-db
    build: ./users/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  movies-service:
    container_name: movies-service
    build: ./movies/
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@movies-db:5432/movies_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@movies-db:5432/movies_test
      - NODE_ENV=development
      - TOKEN_SECRET=blabla
      - USERS_SERVICE_URL=http://localhost:3000
    depends_on:
      movies-db:
        condition: service_healthy
      users-service:
        condition: service_started
    links:
      - movies-db
      - users-service

  users-service:
    container_name: users-service
    build: ./users/
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - NODE_ENV=development
      - TOKEN_SECRET=blabla
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build: ./web/
    ports:
      - '3007:9000'
    environment:
      - NODE_ENV=development
      #- REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      #- REACT_APP_MOVIES_SERVICE_URL=h${REACT_APP_MOVIES_SERVICE_URL}
      - REACT_APP_MOVIES_SERVICE_URL=http://localhost:3001
      - REACT_APP_USERS_SERVICE_URL=http://localhost:3000
    depends_on:
      users-service:
        condition: service_started
      movies-service:
        condition: service_started
    links:
      - users-service
      - movies-service
